# This is a basic workflow to help you get started with Actions

name: Task 2 - Lab 3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello world!"

      - name: List Directory with ls command
        run: ls

      - name: Show the current path
        run: pwd

      - name: Show the date
        run: date
