# This is a basic workflow to help you get started with Actions

name: Task 2 - Lab 3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      # first action
      - name: Run a one-line script
        run: echo "Hello world!"

      # second action
      - name: List Directory with ls command
        run: ls

      # third action
      - name: show the path currently at with pwd
        run: pwd
      # 4th action
      - name: show the date
        run: date
